Portfolio Setup and Mobile First: Add index.html, style.css and Linters
rmiyoyo/Portfolio-Setup-and-Mobile-First pull request #1
Opened 2023-03-23 21:53 UTC by rmiyoyo

- Added the ```index.html```, ```style.css``` files and images for the portfolio site
- Added the HTML/CSS linters to check for errors.
- Implemented flexbox

2023-03-23 22:36 UTC, OyePriscilla requested changes
Hi @rmiyoyo 👍 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Linters check passed ✔️
Observed GitHub Flow ✔️
Content is aligned with flexbox ✔️
Used images and background-image to enhance the look of the website ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 22:36 UTC, OyePriscilla commented on index.html
> +      <a href="#" class="logo">My Logo</a>
- [ ] Please kindly bring the logo out of the `nav` tag, a logo is not supposed to be part of the navigation links. 👍

2023-03-23 22:36 UTC, OyePriscilla commented on index.html
> +  <div class="container">
- [ ] Please for semantics purpose, kindly use the `header` tag in place of the div tag. The [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) header element represents introductory content, typically a group of introductory or navigational aids. 👍

2023-03-23 22:36 UTC, OyePriscilla commented on index.html
> +  </div>
- [ ]  The container of this section suppose to be a `section` not `div` tag. It represents a generic standalone section of the document. 👍

2023-03-23 22:36 UTC, OyePriscilla commented on index.html
> +        <a href="#"><img src="./images/icons/random.svg" alt="Random"></a>
- [ ]  Kindly use a `ul` tag to group the list of these images, and `li` per icon; each icon has a link (a tag). Apart from being semantically correct, the a tag will let you connect your social networks with the icons, using `href`. 👍

2023-03-23 22:36 UTC, OyePriscilla commented on style.css
> +}
- [ ] Please kindly take note of the general structure of your design when compared to the given template. I couldn't see the `left-border-bottom` radius and more so, all the background images are not showing. Please ensure to align all the elements on the page according to the given template. Our ability to reproduce perfectly a given design shows that we pay attention to details. 👍 

## Figma design
<img width="141" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/227379198-c625d3b2-8781-49da-8260-f2d7812506bf.png">

## Your design
<img width="300" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/227379363-122774bc-a76f-486c-a3aa-2fe56f505c01.png">

2023-03-24 01:17 UTC, rmiyoyo commented
# Work Done After Review
- Removed logo from ```nav``` tag
- Adjusted the alignment of sections to be uniform
- Added ```header``` tag after the main container ```div```
- Replaced ```div``` with ```section``` tag in the social media icons
- Used an unordered list in the social media section
- Revised general structure of the design to include all background images and alignments

2023-03-24 01:26 UTC, Shedrack-Sunday approved these changes
# STATUS: APPROVED ♻️♻️
Hi @rmiyoyo 

To highlight 👍🏽
✔️ Proper use Semantics
✔️ No linter errors

Your project is complete! There is nothing else to say other than... it's time to merge it 🚀
Congratulations! 🎉

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-03-24 01:38 UTC, merged